<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Beeromat</title>

        <?php echo $this->headLink()->appendStylesheet('/css/global.css') ?>

        <?php echo $this->jQuery(); ?>

        <?php
//            $this->headScript()->appendFile('/js/bootstrap/bootstrap.min.js');
//            $this->headScript()->appendFile('/js/jquery/js/jquery-ui-1.10.4.custom.min.js');
//            $this->headScript()->appendFile('/js/Menu.js');
//
//            echo $this->headScript();            
        ?>


    </head>
    <body>
        <div class="content">   
            <p class="header">
                <img id="imgBerry" src="/img/berry.png"/>  
            </p> 
           
            <?php echo $this->layout()->content ?>

        </div>

    </body>
</html>